[build]
builder = "NIXPACKS"
watchPatterns = ["clarivore-menu-monitor/**"]

[deploy]
startCommand = "node clarivore-menu-monitor/src/index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
